package backup

import (
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Manager handles workspace git snapshots and binary backups.
type Manager struct {
	workspaceRoot string
	binaryPath    string
	maxVersions   int
	enabled       bool
}

func New(workspaceRoot, binaryPath string, maxVersions int, enabled bool) *Manager {
	return &Manager{
		workspaceRoot: workspaceRoot,
		binaryPath:    binaryPath,
		maxVersions:   maxVersions,
		enabled:       enabled,
	}
}

// InitWorkspaceGit initializes a git repo in the workspace if not already present.
func (m *Manager) InitWorkspaceGit() error {
	if !m.enabled {
		return nil
	}

	// Write .gitignore to exclude .env files and secrets
	gitignore := filepath.Join(m.workspaceRoot, ".gitignore")
	if _, err := os.Stat(gitignore); os.IsNotExist(err) {
		content := "# Auto-generated by clawdbot\n.env\n*.env\nnode_modules/\n__pycache__/\n*.pyc\n"
		if err := os.WriteFile(gitignore, []byte(content), 0644); err != nil {
			log.Printf("backup: failed to write .gitignore: %v", err)
		}
	}

	gitDir := filepath.Join(m.workspaceRoot, ".git")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		if err := m.git("init"); err != nil {
			return fmt.Errorf("git init: %w", err)
		}
		// Initial commit
		m.git("add", "-A")
		m.git("commit", "-m", "initial workspace checkpoint", "--allow-empty")
		log.Printf("backup: initialized git repo in %s", m.workspaceRoot)
	}
	return nil
}

// Checkpoint creates a git checkpoint tagged as 'last-good'.
// Call this after successful startup / health check.
func (m *Manager) Checkpoint() error {
	if !m.enabled {
		return nil
	}

	tag := fmt.Sprintf("checkpoint-%s", time.Now().Format("20060102T150405"))

	if err := m.git("add", "-A"); err != nil {
		log.Printf("backup: add failed: %v", err)
	}
	if err := m.git("commit", "-m", "checkpoint: "+time.Now().Format(time.RFC3339), "--allow-empty"); err != nil {
		log.Printf("backup: commit failed: %v", err)
	}
	if err := m.git("tag", "-f", "last-good"); err != nil {
		log.Printf("backup: tag last-good failed: %v", err)
	}
	if err := m.git("tag", tag); err != nil {
		log.Printf("backup: tag %s failed: %v", tag, err)
	}

	// Prune old checkpoints
	if err := m.pruneOldCheckpoints(); err != nil {
		log.Printf("backup: prune error: %v", err)
	}

	log.Printf("backup: checkpoint created (%s)", tag)
	return nil
}

// PreChange creates a pre-change snapshot before AI modifies code.
func (m *Manager) PreChange() error {
	if !m.enabled {
		return nil
	}
	tag := fmt.Sprintf("pre-change-%d", time.Now().Unix())
	m.git("add", "-A")
	m.git("commit", "-m", "pre-change snapshot", "--allow-empty")
	if err := m.git("tag", tag); err != nil {
		return fmt.Errorf("pre-change tag: %w", err)
	}
	log.Printf("backup: pre-change snapshot: %s", tag)
	return nil
}

// Rollback restores the workspace to the last-good tag (or specified tag).
func (m *Manager) Rollback(tag string) error {
	if tag == "" {
		tag = "last-good"
	}
	if err := m.git("checkout", tag, "--", "."); err != nil {
		return fmt.Errorf("git checkout %s: %w", tag, err)
	}
	log.Printf("backup: rolled back workspace to %s", tag)
	return nil
}

// ListCheckpoints returns all checkpoint tags, most recent first.
func (m *Manager) ListCheckpoints() ([]string, error) {
	out, err := m.gitOutput("tag", "--sort=-creatordate", "-l", "checkpoint-*")
	if err != nil {
		return nil, err
	}
	tags := strings.Split(strings.TrimSpace(out), "\n")
	var result []string
	for _, t := range tags {
		if t != "" {
			result = append(result, t)
		}
	}
	return result, nil
}

// BackupBinary copies the current binary to binaryPath.backup.
func (m *Manager) BackupBinary() error {
	if !m.enabled || m.binaryPath == "" {
		return nil
	}

	src := m.binaryPath
	dst := m.binaryPath + ".backup"

	if _, err := os.Stat(src); os.IsNotExist(err) {
		return nil // binary doesn't exist yet (e.g. in dev)
	}

	if info, err := os.Stat(dst); err == nil && info.IsDir() {
		return fmt.Errorf("backup binary: destination %s is a directory", dst)
	}

	if err := copyFile(src, dst); err != nil {
		return fmt.Errorf("backup binary: %w", err)
	}
	log.Printf("backup: binary backed up to %s", dst)
	return nil
}

// RestoreBinary restores the binary from backup.
func (m *Manager) RestoreBinary() error {
	if !m.enabled || m.binaryPath == "" {
		return nil
	}

	src := m.binaryPath + ".backup"
	dst := m.binaryPath

	if _, err := os.Stat(src); os.IsNotExist(err) {
		return fmt.Errorf("no binary backup found at %s", src)
	}

	if err := copyFile(src, dst); err != nil {
		return fmt.Errorf("restore binary: %w", err)
	}
	log.Printf("backup: binary restored from backup")
	return nil
}

// pruneOldCheckpoints deletes the oldest checkpoint tags beyond maxVersions.
func (m *Manager) pruneOldCheckpoints() error {
	if m.maxVersions <= 0 {
		return nil
	}

	checkpoints, err := m.ListCheckpoints()
	if err != nil {
		return err
	}

	// Sort by time (tag format: checkpoint-YYYYMMDDTHHMMSS)
	sort.Sort(sort.Reverse(sort.StringSlice(checkpoints)))

	if len(checkpoints) <= m.maxVersions {
		return nil
	}

	toDelete := checkpoints[m.maxVersions:]
	for _, tag := range toDelete {
		if err := m.git("tag", "-d", tag); err != nil {
			log.Printf("backup: failed to delete old checkpoint %s: %v", tag, err)
		} else {
			log.Printf("backup: deleted old checkpoint %s", tag)
		}
	}
	return nil
}

func (m *Manager) git(args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = m.workspaceRoot
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %v: %w (output: %s)", args, err, string(out))
	}
	return nil
}

func (m *Manager) gitOutput(args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = m.workspaceRoot
	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("git %v: %w (stderr: %s)", args, err, string(exitErr.Stderr))
		}
		return "", err
	}
	return string(out), nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	info, err := in.Stat()
	if err != nil {
		return err
	}

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, info.Mode())
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}
